---
title: "What would be different if everyone votes?"
subtitle: ""
author: "Linzi Guan"
thanks: "Code and data are available at: "
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: |
  | Observing the significant political influence of low voter turnout and huge different between the predicted results of election in polls and in real world, this paper analyses the issues of low voter turnout and aims to find what would be different if everyone votes. Datasets about ... are obtained, cleaned and analysed with a statistical Multilevel regression model with post stratification. Based on the model, ... is found. The results and the study appeal for politicans to predict the final results of the election taking everyones' vote and thus to come up policies that call people to vote. 

  |
  | **Keywords:** Political participation, Low voter turnout, 2019 US eletion, TBD
output: pdf_document
toc: FALSE
#bibliography: references.bib

---

# Introduction

Political participation has always been a sharp issue in the elections and low voter turnout and inequalities have significant political and policy consequences(@ article to be citied). Due to the low voter turnout, the results of public opinion poll have large gap and sometimes even huge difference from the true, final results. Eyes on the issues of low voter turnout and the difference betwwen poll and the actual results, a question to be asked is what would be different if everyone votes. In this paper, a Multilevel logistic regression model with poststratification is conducted according to the CES(@reference) and a post-stratification dataset(to be obtained) in R (@cite R) and findings on the importance of turnout based on the model and results are discussed. 

Based on the datasets, I have applied a statistical method to build one multilevel logis tic regression models with post-stratification in this analysis to predict the polling result if everyone has voted in 2019 US election. I have learned that ...(results to be found) After ...(how to conduct the model), I found ...(results of the model). Observing that(points to be noticed in the model), I ...(adjustments of the model). Then based on the results of the model, I predicted that ...(predictions from the model)

The paper is organized in the following parts with a full disclosure and analysis of the data I used to built my study in the Data Section, some detailed discussions on the statistical models that I used for forecasting in Model Section, some discussions and results, and also some limitations and nextsteps.

# Data

The two datasets that are used in this paper for analysis involve ... and .... The main features are as following:
Undetermined

# Model

# Discussion
Undetermined

# Limitations and next steps
Undetermined

# Reference
https://dash.harvard.edu/bitstream/handle/1/11156810/Fowler_gsas.harvard_0084L_10773.pdf?sequence=3
R